doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    types:
      ip: Darsyn\IP\Doctrine\MultiType
      ipv4: Darsyn\IP\Doctrine\IPv4Type
      ipv6: Darsyn\IP\Doctrine\IPv6Type

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
